version: 3
projects:
- name: default
  dir: .
  workspace: default
  terraform_version: v0.12.19
  autoplan:
    when_modified: ["*.tf", "../modules/**.tf"]
    enabled: true
  apply_requirements: [mergeable, approved]
  workflow: 
    default:
      plan:
        steps:
          - run: terraform plan -no-color -out "${PLANFILE}"
      apply:
        steps:
          - run: terraform apply -no-color "${PLANFILE}"